dist: trusty
language: node_js
services:
  - docker
sudo: false
node_js: 
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
stages:
  - name: linter
  - name: unit-tests
  - name: e2e
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: linter
      script: npm run lint
    - stage: unit-tests
      script: bash ./ci/unit-tests
    - stage: e2e
      script: npm run e2e
    - stage: deploy
      script: bash ./ci/deploy && bash ./ci/release
